[variables]
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
CI = "false"
GENERATE_SOURCEMAP = "false"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["cd client && npm install --legacy-peer-deps && npm run build"]

[start]
cmd = "npm start" 