[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "cd client && GENERATE_SOURCEMAP=false CI=false npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
CI = "false" 